name: pybox2d
channels:
  - conda-forge
dependencies:
  - python=3.6
  - numpy=1.13.1
  - scipy=0.19.1
  - pygame=2.6.1
  - gym=0.19.0
  - cloudpickle=1.6.0
  - pip
  - pip:
    - Box2D==2.3.10
    - certifi==2024.8.30
    - charset-normalizer==2.0.12
    - docopt==0.6.2
    - future==0.16.0
    - idna==3.10
    - pyglet==1.5.16
    - requests==2.27.1
    - urllib3==1.26.20
    - yarg==0.1.10
    - torch==2.4.1
    - imageio~=2.15.0
    - matplotlib==3.7.5
    - numpy==1.24.4
    - tensorflow==2.7.0
    - mageio==2.15.0
